name: CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
